### ISSUE TITLE
How can I visit sails controller/action via get method?

### ISSUE THREAD

**Issue by tonyts** [Tarrask/sails-hook-webpack-vue#1]
I have a `UserController `and a `User` model, managing users with sails Blueprint API, and I try to use `io.socket.get('/user', cb)` to monitor the users' status. But I find that in dev mode, all get method route to index.html. How can I visit sails controller/action via get method?

**Comment by tonyts** [comment]
sorry, I think I submit the issue to the wrong repo, please ignore.

**Comment by Tarrask** [comment]
Hi,

I guess you was at the correct place. 

In the 0.1.3 version, the `historyFallback` middleware was triggered before the sails router, masking every routes declared in sails.

I fixed that in 0.1.4, the historyFallback middleware is now inserted just after the router, so the sails route will work, and when no route are found, the historyFallback will try to serve the index.html file.

Hope this can help you

**Comment by tonyts** [comment]
Thank you
